"""
Note:
The code for this script was generated by a Google search using AI.
Since Alfonso Blanco has me located in Spain, he kindly generated  the comments in Spanish,
which is a disadvantage for readers who don't speak Spanish.

Preguntando a la IA de Google

python program para estimar distancias de coches en una foto usando yolo26n-depth 

Para lograr esto, se utiliza la librería oficial de Ultralytics.
A partir del ecosistema moderno de YOLO (como las tareas nativas de estimación monocular introducidas en Ultralytics),
el modelo especializado yolo26n-depth procesa la imagen y devuelve un mapa de profundidad denso,
donde cada píxel contiene la distancia estimada en metros directamente desde la cámara. [1, 2, 3] 
Para estimar la distancia de los coches, primero se detectan sus coordenadas mediante un modelo de detección estándar
(como yolo26n.pt) y luego se extrae el valor correspondiente del mapa de profundidad generado por yolo26n-depth.pt. [3, 4]

Requisitos Previos

Instala la versión actualizada de Ultralytics y las librerías necesarias:

pip install ultralytics opencv-python numpy

Ultralytics tiene que estar actualizado a la ultima versión: pip install --upgrade ultralytics
Si se mantiene una versión antigua puede dar problemas

Código en Python
"""
#Este programa realiza la detección del coche, calcula su mapa de profundidad absoluto y promedia
# la distancia del centro del vehículo. [4, 5]

import cv2
import numpy as np
from ultralytics import YOLO

def estimar_distancia_coches(ruta_imagen):
    # 1. Cargar los modelos oficiales de Ultralytics
    # El modelo estándar detecta las cajas del coche; el modelo -depth estima los metros
    model_det = YOLO("yolo26n.pt")
    model_depth = YOLO("yolo26n-depth.pt")
    
    # 2. Cargar la imagen de entrada
    img = cv2.imread(ruta_imagen)
    if img is None:
        print("Error: No se pudo cargar la imagen.")
        return

    # 3. Obtener el mapa de profundidad monocular (en metros)
    resultado_depth = model_depth(img) #MOD
    # El mapa de profundidad viene en formato tensor flotante alineado a la imagen
    mapa_profundidad = resultado_depth[0].depth.data.cpu().numpy().squeeze() 

    # 4. Detectar objetos en la imagen
    resultado_det = model_det(img)[0]
    cajas = resultado_det.boxes

    # 5. Iterar sobre los objetos detectados buscando coches
    for caja in cajas:
        cls_id = int(caja.cls[0])
        nombre_clase = model_det.names[cls_id]
        
        # Filtrar únicamente coches (clase 'car' en el dataset COCO es ID 2)
        if nombre_clase == "car":
            # Extraer coordenadas de la caja delimitadora (Bounding Box)
            x1, y1, x2, y2 = map(int, caja.xyxy[0])
            
            # Definir una región central dentro del coche para evitar el fondo exterior
            ancho_caja = x2 - x1
            alto_caja = y2 - y1
            cx1 = int(x1 + ancho_caja * 0.3)
            cx2 = int(x1 + ancho_caja * 0.7)
            cy1 = int(y1 + alto_caja * 0.3)
            cy2 = int(y1 + alto_caja * 0.7)
            
            # Recortar la zona del mapa de profundidad correspondiente al coche
            zona_coche_depth = mapa_profundidad[cy1:cy2, cx1:cx2]
            
            # Calcular la distancia mediana (más robusta que el promedio ante ruidos)
            distancia_metros = np.median(zona_coche_depth)
            
            # 6. Dibujar los resultados sobre la imagen original
            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
            texto = f"Car: {distancia_metros:.2f}m"
            cv2.putText(img, texto, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

    # 7. Guardar y mostrar el resultado visualizado
    #cv2.imwrite("resultado_distancia.jpg", img)
    #cv2.imshow("Estimacion de Distancia - Coches", img)
    #cv2.waitKey(0)
    #cv2.destroyAllWindows()
    return img

# Ejecutar la función con tu imagen
#if __name__ == "__main__":
#    estimar_distancia_coches("pp.jpg")

